// SPDX-License-Identifier: Apache-2.0
//! Compare baiez with the native scores generated by measure_lightgbm.py.
//!
//! `cargo run --release --example measure_real -- /tmp/baiez-lightgbm-measure`

use std::error::Error;
use std::hint::black_box;
use std::time::{Duration, Instant};

use baiez::{IndexedRow, Model, PackedIndex, PredictOptions, Prediction, PreparedIndex};
use yesno_core::Db;

fn doubles(path: &std::path::Path) -> Result<Vec<f64>, Box<dyn Error>> {
    let bytes = std::fs::read(path)?;
    if !bytes.len().is_multiple_of(8) {
        return Err("f64 file has a partial value".into());
    }
    Ok(bytes
        .chunks_exact(8)
        .map(|part| f64::from_le_bytes(part.try_into().unwrap()))
        .collect())
}

fn allocated_bytes(path: &std::path::Path) -> std::io::Result<u64> {
    #[cfg(unix)]
    use std::os::unix::fs::MetadataExt;
    let mut total = 0;
    for entry in std::fs::read_dir(path)? {
        let entry = entry?;
        let metadata = entry.metadata()?;
        if metadata.is_dir() {
            total += allocated_bytes(&entry.path())?;
        } else {
            #[cfg(unix)]
            {
                total += metadata.blocks() * 512;
            }
            #[cfg(not(unix))]
            {
                total += metadata.len();
            }
        }
    }
    Ok(total)
}

fn scalar(model: &Model, features: &[[f64; 8]], ids: &[u64]) -> Vec<Prediction> {
    ids.iter()
        .map(|id| {
            model
                .predict_scalar(
                    &features[*id as usize],
                    PredictOptions {
                        raw_score: true,
                        ..Default::default()
                    },
                )
                .unwrap()
        })
        .collect()
}

fn median(mut timings: Vec<Duration>, repetitions: usize) -> f64 {
    timings.sort_unstable();
    timings[timings.len() / 2].as_secs_f64() * 1e6 / repetitions as f64
}

fn time_case(mut run: impl FnMut(), repetitions: usize) -> f64 {
    let mut timings = Vec::with_capacity(7);
    for _ in 0..7 {
        let start = Instant::now();
        for _ in 0..repetitions {
            run();
        }
        timings.push(start.elapsed());
    }
    median(timings, repetitions)
}

#[allow(clippy::too_many_arguments)]
fn case(
    shape: &str,
    ids: &[u64],
    model: &Model,
    features: &[[f64; 8]],
    native: &[f64],
    index: &PackedIndex,
    snapshot: &yesno_core::Snapshot,
    prepared: &PreparedIndex,
) -> Result<(), Box<dyn Error>> {
    let options = PredictOptions {
        raw_score: true,
        ..Default::default()
    };
    let expected = scalar(model, features, ids);
    let actual = index.predict(snapshot, model, ids, options)?;
    let mut flat_scores = vec![0.0; ids.len()];
    prepared.predict_into(ids, options, &mut flat_scores, None)?;
    let mut max_error = 0.0f64;
    for (((id, scalar), packed), flat) in ids.iter().zip(&expected).zip(&actual).zip(&flat_scores) {
        let native_value = native[*id as usize];
        max_error = max_error.max((scalar.scores[0] - native_value).abs());
        max_error = max_error.max((packed.scores[0] - native_value).abs());
        max_error = max_error.max((flat - native_value).abs());
    }
    if max_error > 1e-10 {
        return Err(format!("{shape}: maximum raw-score error {max_error}").into());
    }
    let repetitions = match ids.len() {
        0..=64 => 30,
        65..=1024 => 12,
        1025..=8192 => 5,
        _ => 2,
    };
    let scalar_us = time_case(
        || {
            black_box(scalar(model, features, black_box(ids)));
        },
        repetitions,
    );
    let packed_us = time_case(
        || {
            black_box(
                index
                    .predict(snapshot, model, black_box(ids), options)
                    .unwrap(),
            );
        },
        repetitions,
    );
    let prepared_us = time_case(
        || {
            black_box(prepared.predict(black_box(ids), options).unwrap());
        },
        repetitions,
    );
    let flat_us = time_case(
        || {
            prepared
                .predict_into(black_box(ids), options, black_box(&mut flat_scores), None)
                .unwrap();
            black_box(&flat_scores);
        },
        repetitions,
    );
    println!(
        "{shape},{},{scalar_us:.3},{packed_us:.3},{prepared_us:.3},{flat_us:.3},{max_error:.3e}",
        ids.len()
    );
    Ok(())
}

fn main() -> Result<(), Box<dyn Error>> {
    let directory = std::env::args()
        .nth(1)
        .ok_or("usage: measure_real FIXTURE_DIR")?;
    let directory = std::path::Path::new(&directory);
    let model = Model::from_dump_json(&std::fs::read_to_string(directory.join("model.json"))?)?;
    if model.num_features() != 8 {
        return Err("fixture model does not have eight features".into());
    }
    let feature_values = doubles(&directory.join("rows.f64"))?;
    if !feature_values.len().is_multiple_of(8) {
        return Err("feature file has a partial row".into());
    }
    let features: Vec<[f64; 8]> = feature_values
        .chunks_exact(8)
        .map(|part| part.try_into().unwrap())
        .collect();
    let native = doubles(&directory.join("native_scores.f64"))?;
    let rows = features.len();
    if native.len() != rows {
        return Err("native score count does not match feature rows".into());
    }
    let indexed: Vec<_> = features
        .iter()
        .enumerate()
        .map(|(id, features)| IndexedRow {
            id: id as u64,
            features,
        })
        .collect();
    let temp = tempfile::tempdir()?;
    let db = Db::open(temp.path())?;
    let build_start = Instant::now();
    let index = PackedIndex::build(&db, &model, 1, &indexed)?;
    let build_seconds = build_start.elapsed().as_secs_f64();
    let checkpoint_start = Instant::now();
    db.checkpoint()?;
    let checkpoint_seconds = checkpoint_start.elapsed().as_secs_f64();
    let disk_bytes = allocated_bytes(temp.path())?;
    let snapshot = db.snapshot()?;
    let prepare_start = Instant::now();
    let prepared = index.prepare(&snapshot, &model)?;
    let prepare_us = prepare_start.elapsed().as_secs_f64() * 1e6;
    let memberships = snapshot.cardinality(1)?;
    println!(
        "setup: rows={rows} trees={} predicates={} memberships={memberships} build_s={build_seconds:.3} checkpoint_s={checkpoint_seconds:.3} prepare_us={prepare_us:.1} allocated_bytes={disk_bytes}",
        model.num_iterations(),
        model.num_predicates()
    );
    println!("shape,rows,scalar_us,packed_us,prepared_us,flat_us,max_abs_error_vs_lightgbm");
    for &size in &[1usize, 64, 1024, 8192, rows] {
        if size > rows {
            continue;
        }
        let begin = (rows - size) / 2;
        let contiguous: Vec<u64> = (begin..begin + size).map(|id| id as u64).collect();
        case(
            "contiguous",
            &contiguous,
            &model,
            &features,
            &native,
            &index,
            &snapshot,
            &prepared,
        )?;
        if size > 1 && size < rows {
            let scattered: Vec<u64> = (0..size)
                .map(|i| ((i as u128 * rows as u128) / size as u128) as u64)
                .collect();
            case(
                "scattered",
                &scattered,
                &model,
                &features,
                &native,
                &index,
                &snapshot,
                &prepared,
            )?;
            if size == 8192 {
                let shuffled: Vec<u64> = (0..size).map(|i| scattered[(i * 4051) % size]).collect();
                case(
                    "scattered_shuffled",
                    &shuffled,
                    &model,
                    &features,
                    &native,
                    &index,
                    &snapshot,
                    &prepared,
                )?;
            }
        }
    }
    Ok(())
}
