#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Attest the yesnodb bundle workflow against saved LightGBM scores.

First build both targets and provide NumPy in the active Python environment:
    cargo build --offline --features python --bin baiez --lib
    python3 scripts/attest_workflow.py /tmp/baiez-lightgbm-measure

The fixture is generated by scripts/measure_lightgbm.py in an environment
with LightGBM. This check uses its saved native raw scores, so running the
attestation itself does not need the LightGBM package.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import math
import pathlib
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from typing import Any

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
CLI = ROOT / "target/debug/baiez"
EXTENSION = ROOT / "target/debug/libbaiez.so"
TOLERANCE = 1e-10


def sha256_file(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def import_adapter() -> Any:
    """Import the built extension in place without requiring maturin."""
    spec = importlib.util.spec_from_file_location("baiez._baiez", EXTENSION)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load extension at {EXTENSION}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["baiez._baiez"] = module
    spec.loader.exec_module(module)
    sys.path.insert(0, str(ROOT / "python"))
    import baiez.lightgbm as lgb

    return lgb


def cli(*args: object, expect_success: bool = True) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        [str(CLI), *(str(arg) for arg in args)],
        capture_output=True,
        text=True,
        check=False,
    )
    if expect_success and result.returncode:
        raise RuntimeError(f"baiez {' '.join(map(str, args))}: {result.stderr}")
    if not expect_success and not result.returncode:
        raise AssertionError(f"expected baiez {' '.join(map(str, args))} to fail")
    return result


def write_rows(path: pathlib.Path, features: np.ndarray) -> None:
    with path.open("w", encoding="utf-8") as stream:
        stream.write("[")
        for row_id, row in enumerate(features):
            if row_id:
                stream.write(",")
            json.dump(
                {
                    "id": row_id,
                    "features": [
                        None if math.isnan(value) else float(value) for value in row
                    ],
                },
                stream,
                allow_nan=False,
                separators=(",", ":"),
            )
        stream.write("]")


def cohorts(count: int) -> list[tuple[str, np.ndarray]]:
    result = []
    for size in dict.fromkeys((1, 64, 1024, 8192, count)):
        if size > count:
            continue
        begin = (count - size) // 2
        result.append(
            (f"contiguous_{size}", np.arange(begin, begin + size, dtype=np.uint64))
        )
        if 1 < size < count:
            scattered = np.arange(size, dtype=np.uint64) * count // size
            result.append((f"scattered_{size}", scattered))
            multiplier = 4051 if size == 8192 else 13
            result.append(
                (
                    f"scattered_shuffled_{size}",
                    scattered[(np.arange(size) * multiplier) % size],
                )
            )
    return result


def check_scores(actual: np.ndarray, expected: np.ndarray, label: str) -> float:
    if actual.shape != expected.shape:
        raise AssertionError(f"{label}: shape {actual.shape} != {expected.shape}")
    error = float(np.max(np.abs(actual - expected)))
    if not np.isfinite(error) or error > TOLERANCE:
        raise AssertionError(f"{label}: maximum absolute error {error}")
    return error


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: attest_workflow.py FIXTURE_DIR")
    fixture = pathlib.Path(sys.argv[1])
    manifest_path = fixture / "manifest.json"
    if manifest_path.exists():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        for filename, expected in manifest["sha256"].items():
            actual = sha256_file(fixture / filename)
            if actual != expected:
                raise AssertionError(f"fixture hash mismatch: {filename}")
    model_path = fixture / "model.json"
    model_bytes = model_path.read_bytes()
    model = json.loads(model_bytes)
    columns = model["max_feature_idx"] + 1
    features = np.fromfile(fixture / "rows.f64", dtype="<f8").reshape((-1, columns))
    native_scores = np.fromfile(fixture / "native_scores.f64", dtype="<f8")
    if len(native_scores) != len(features):
        raise AssertionError("fixture score count differs from row count")
    lgb = import_adapter()

    with tempfile.TemporaryDirectory(prefix="baiez-attest-") as workspace:
        work = pathlib.Path(workspace)
        db = work / "db"
        rows_json = work / "rows.json"
        ids_json = work / "ids.json"
        write_rows(rows_json, features)

        # Atomic model + index load, exact JSON dump, and an expected native
        # dump failure: JSON input has no source LightGBM text to round-trip.
        cli(
            "model",
            "load",
            "--db",
            db,
            "--key",
            9000,
            "--input",
            model_path,
            "--format",
            "json",
            "--rows",
            rows_json,
        )
        dumped = work / "dumped.json"
        cli(
            "model",
            "dump",
            "--db",
            db,
            "--key",
            9000,
            "--format",
            "json",
            "--output",
            dumped,
        )
        if dumped.read_bytes() != model_bytes:
            raise AssertionError("JSON dump did not match input bytes")
        cli(
            "model",
            "dump",
            "--db",
            db,
            "--key",
            9000,
            "--format",
            "lightgbm",
            "--output",
            work / "native.txt",
            expect_success=False,
        )

        booster = lgb.Booster.from_yesno(str(db), 9000)
        if booster.dump_model() != model:
            raise AssertionError("Python bundle dump differs from input model")

        results = []
        for name, ids in cohorts(len(features)):
            ids_json.write_text(json.dumps(ids.tolist()), encoding="utf-8")
            response = cli(
                "predict", "--db", db, "--key", 9000, "--ids", ids_json, "--raw"
            )
            cli_scores = np.array(
                [prediction["scores"][0] for prediction in json.loads(response.stdout)],
                dtype=np.float64,
            )
            py_scores = booster.predict_ids(ids, raw_score=True)
            marked_scores = booster.predict(lgb.IndexedRows(ids), raw_score=True)
            expected = native_scores[ids]
            cli_error = check_scores(cli_scores, expected, f"CLI {name}")
            py_error = check_scores(py_scores, expected, f"Python {name}")
            if not np.array_equal(py_scores, marked_scores):
                raise AssertionError(f"{name}: Python indexed prediction routes differ")
            results.append(
                {
                    "cohort": name,
                    "rows": len(ids),
                    "cli_max_abs_error": cli_error,
                    "python_max_abs_error": py_error,
                }
            )

        # Check the Booster-style leaf shape and iteration window across the
        # CLI and Python adapters on rows with distinct branch paths.
        leaf_ids = np.arange(64, dtype=np.uint64) * len(features) // 64
        ids_json.write_text(json.dumps(leaf_ids.tolist()), encoding="utf-8")
        leaf_response = json.loads(
            cli(
                "predict",
                "--db",
                db,
                "--key",
                9000,
                "--ids",
                ids_json,
                "--raw",
                "--leaf",
                "--start=4",
                "--count=3",
            ).stdout
        )
        cli_leaves = np.array(
            [prediction["leaves"] for prediction in leaf_response], dtype=np.uint64
        )
        py_leaves = booster.predict(
            lgb.IndexedRows(leaf_ids),
            pred_leaf=True,
            start_iteration=4,
            num_iteration=3,
        )
        if py_leaves.shape != (64, 3) or not np.array_equal(cli_leaves, py_leaves):
            raise AssertionError("leaf indices or iteration window differ")
        py_window_scores = booster.predict_ids(
            leaf_ids, raw_score=True, start_iteration=4, num_iteration=3
        )
        cli_window_scores = np.array([p["scores"][0] for p in leaf_response])
        if not np.array_equal(py_window_scores, cli_window_scores):
            raise AssertionError("iteration-window scores differ")

        try:
            booster.predict_ids(np.array([len(features)], dtype=np.uint64))
        except RuntimeError:
            pass
        else:
            raise AssertionError("missing row ID was accepted")

        # Exercise the separate model-load and index-build path as well.
        cli(
            "model",
            "load",
            "--db",
            db,
            "--key",
            9002,
            "--input",
            model_path,
            "--format",
            "json",
        )
        ids_json.write_text("[0]", encoding="utf-8")
        cli(
            "predict",
            "--db",
            db,
            "--key",
            9002,
            "--ids",
            ids_json,
            "--raw",
            expect_success=False,
        )
        cli("index", "build", "--db", db, "--key", 9002, "--rows", rows_json)
        separate = json.loads(
            cli("predict", "--db", db, "--key", 9002, "--ids", ids_json, "--raw").stdout
        )
        check_scores(
            np.array([separate[0]["scores"][0]]),
            native_scores[:1],
            "separate load/index",
        )

    report = {
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "fixture": str(fixture),
        "sha256": {
            "model_json": sha256_file(model_path),
            "model_txt": sha256_file(fixture / "model.txt"),
            "rows_f64": sha256_file(fixture / "rows.f64"),
            "native_scores_f64": sha256_file(fixture / "native_scores.f64"),
            "cli": sha256_file(CLI),
            "python_extension": sha256_file(EXTENSION),
        },
        "rows": len(features),
        "features": columns,
        "trees": len(model["tree_info"]),
        "missing_values": int(np.isnan(features).sum()),
        "zero_values": int((features == 0.0).sum()),
        "json_dump_exact": True,
        "separate_load_index": True,
        "leaf_window_cli_python_equal": True,
        "missing_row_rejected": True,
        "cohorts": results,
    }
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
